### ISSUE TITLE
busybox in MLD: no grep -P

### ISSUE THREAD

**Issue by herrdeh** [vdr-projects/vdr-convert#1]
I tried on MLD 5.5. That shell does not know grep -P and so the script does not work. What can be done?
Here are error messages:

`3MLD> vdr-convert.sh -f mkv -i "2022-10-17.20.42.3-0.rec/"
------------------------------------------------------------------------------------------------------------------------

vdr-convert: Processing '2022-10-17.20.42.3-0.rec/' (files=1), keep=0, delete=0, combine=0, format=mkv, subs=1, extras=, podcast dir=
grep: invalid option -- 'P'
BusyBox v1.25.1 (2021-08-05 14:40:33 UTC) multi-call binary.

Usage: grep [-HhnlLoqvsriwFE] [-m N] [-A/B/C N] PATTERN/-e PATTERN.../-f FILE [FILE]...

Search for PATTERN in FILEs (or stdin)

	-H	Add 'filename:' prefix
	-h	Do not add 'filename:' prefix
	-n	Add 'line_no:' prefix
	-l	Show only names of files that match
	-L	Show only names of files that don't match
	-c	Show only count of matching lines
	-o	Show only the matching part of line
	-q	Quiet. Return 0 if PATTERN is found, 1 otherwise
	-v	Select non-matching lines
	-s	Suppress open and read errors
	-r	Recurse
	-i	Ignore case
	-w	Match whole words only
	-x	Match whole lines only
	-F	PATTERN is a literal (not regexp)
	-E	PATTERN is an extended regexp
	-m N	Match up to N times per file
	-A N	Print N lines of trailing context
	-B N	Print N lines of leading context
	-C N	Same as '-A N -B N'
	-e PTRN	Pattern to match
	-f FILE	Read pattern from file

### the above message was repeated 10 times ###

------------------------------------------------------------------------------------------------------------------------
vdr-convert: Processing "2022-10-17.20.42.3-0.rec//00001.ts" file 1, size 765M...
/usr/local/bin/vdr-convert.sh: line 299: 22358 Killed                  nice -n 19 ffmpeg -y -hide_banner -nostats -probesize 250M -analyzeduration 600M -copytb 1 -i "2022-10-17.20.42.3-0.rec//00001.ts" 2>&1
/usr/local/bin/vdr-convert.sh: line 694: + : syntax error: operand expected (error token is "+ ")

------------------------------------------------------------------------------------------------------------------------
ffmpeg stream data for 2022-10-17.20.42.3-0.rec//intermediate-file-1.ts:

Stream scoring: 

stream mapping for 2022-10-17.20.42.3-0.rec//intermediate-file-1.ts:
Map:  
NOTE: -metadata episode_id is missing
NOTE: -metadata description is missing
NOTE: -metadata comment is missing

------------------------------------------------------------------------------------------------------------------------
vdr-convert: Creating output with nice -n 19 ffmpeg -y -hide_banner -nostats -probesize 250M -analyzeduration 600M -copytb 1 -i concat:"2022-10-17.20.42.3-0.rec//intermediate-file-1.ts|"        -metadata service_provider="C-1-1039-10376"      -metadata service_name="ONE HD"      -metadata title="Parlament (2)-Trau, schau, wem!-2022-10-17-Mo_20-40"      -metadata year="2022"      -metadata date="2022"      -metadata album="2022"      -metadata track="42"      -metadata author="ONE HD"      -metadata artist="ONE HD"      -metadata album_artist="Parlament (2)"      -metadata genre="10"            -metadata show="Parlament (2)"                  -metadata language="deu"      -metadata publisher="ONE HD"      -metadata encoder="vdr-convert"      -metadata encoded_by="vdr-convert"       -c copy   "/data/tv/%Parlament_(2)/Parlament (2)-Trau, schau, wem!-2022-10-17-Mo_20-40-.mkv" 2>> /var/log/vdr-convert.log
stat: cannot stat '/data/tv/%Parlament_(2)/Parlament (2)-Trau, schau, wem!-2022-10-17-Mo_20-40-.mkv': No such file or directory

vdr-convert: Created /data/tv/%Parlament_(2)/Parlament (2)-Trau, schau, wem!-2022-10-17-Mo_20-40-.mkv (765M to 0M (0.0%)), Fail
vdr-convert: Fail: Converted files for Parlament (2)-Trau, schau, wem!-2022-10-17-Mo_20-40- did not merge correctly
/usr/local/bin/vdr-convert.sh: line 910: mail: command not found

(standard_in) 1: syntax error
vdr-convert: Completed: Parlament (2)-Trau, schau, wem!-2022-10-17-Mo_20-40-, Runtime: 00:00:37 (0,00X)`

**Comment by keynet** [comment]
Hi,
The problem is that MLD is using busybox which provides only a limited version of the normal grep utility without -P (Perl regex, which I use).  This kind of environment hasn't been tested (requirements state a normal Linux distro with utilities).
I may be able to reduce the need in a future version, but I don't have a test environment for busybox currently. 
For now, can you install a full version of grep to workaround the issue ?  If there's space for ffmpeg etc, this won't be an issue.

**Comment by herrdeh** [comment]
Thank you very much for your time and attention.
I tried to install grep in MLD, but as it is (on purpose) a very minimalistic system, there are some other  dependencies to fulfil, and as MLD does not have aptitude either, I don't have the abilities to resolve them manually.

So - please don't feel rushed, nevertheless I'm looking forward to the next version. 

> I don't have a test environment for busybox
Try MLD - it's so tiny that you can perform a rocket-fast install.

Cheers,
Wolf

**Comment by keynet** [comment]
Hello again.  I made a version that calls the busybox binary instead of grep, so I could test and reproduce your problem.  I modified to see if I could remove the need for the grep -oP, and significant text matching functionality stops working in a few places - the regex constructs I need specifically use PCRE options currently.  I'll look at changing them in future where possible.

**Comment by herrdeh** [comment]
Full grep is now available at MLD.
